import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';
import ResponsiveAppBar from './nav'
import SignIn from './signIn';
import Head from 'next/head';


export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
    <Head>
        <title>Peer Doc Reviewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Component {...pageProps} />
    </>
  );
}
