import "@/styles/globals.css";
import type { AppProps } from "next/app";
import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";
import ResponsiveAppBar from "./nav";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { SnackbarProvider } from "notistack";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <SnackbarProvider maxSnack={3}>
      <SessionProvider session={session}>
        <Head>
          <title>Doc Review</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <ResponsiveAppBar />
        <Component {...pageProps} />
      </SessionProvider>
    </SnackbarProvider>
  );
}
